apiVersion: v1
clusters:
- cluster:
    server: https://10.136.152.227:30013
    insecure-skip-tls-verify: true
  name: local
contexts:
- context:
    cluster: local
    namespace: default
    user: user
  name: Default
current-context: Default
kind: Config
preferences: {}
users:
- name: user
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJQmE5WVFsNUhodnN3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOalE1TnpNeE56RTVNQjRYRFRJeU1EUXhNakF5TkRnek9Wb1hEVEl6TURReApNakF5TkRnek9Wb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJHelU4OWN4SEVXcGVQLzEKWXcrT21TZjM4ZEwxOTdJNGEwbEdZU1JDVjZPQUs5QmVIb2JNOUt0Y0pNa2dlQ2tPeGlCZEtmdFBYZ1Q5SUh0dAppZkhZMVl5alNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCU0c5OXgvaCtzNmMxZ0t3YVRNa3JXa1VtTURWREFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlFQW1meno3Rm9ibFJoVzRsSE1xR3RicXlZMGhWSlpETFR5WFM1UGtJNWNzUFFDSUJuSGtEbUxWSTh4UVh3QwplMS8xcmdrekdoVW9nT3J1alp0SitYWTVVd2xvCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUyTkRrM016RTNNVGt3SGhjTk1qSXdOREV5TURJME9ETTVXaGNOTXpJd05EQTVNREkwT0RNNQpXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUyTkRrM016RTNNVGt3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUaW5ZMkQ3TlBjdnphQnlCUVkrY2tXZHhrS0pNbzNRV0VWcHI0VnlMZDQKbCtrRTk1MTZ5MFN6c3BzeEhFQWt1MWllUTExbklqcEpNWGJtOHFQS2JjRTFvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWh2ZmNmNGZyT25OWUNzR2t6SksxCnBGSmpBMVF3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnQmRNNDF6d1RLNmNVTTdzUU5PSTM5OGNvS2E0MnUveUsKbFU3NVRRUkF6UFlDSVFEaFVBTFJZQ0ErZVYzNGdmMWtzTnJQNzE2cUtkZzh3d01oYWp3THUwK1EvUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUtUdzYzWXVkZ0lUMithL0ZKcmdidUdCSFdORVp3VTJTN3hJU1BYOE1CRklvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFYk5UejF6RWNSYWw0Ly9WakQ0NlpKL2Z4MHZYM3NqaHJTVVpoSkVKWG80QXIwRjRlaHN6MApxMXdreVNCNEtRN0dJRjBwKzA5ZUJQMGdlMjJKOGRqVmpBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
