apiVersion: v1
clusters:
- cluster:
    server: https://10.136.152.227:30012
    insecure-skip-tls-verify: true
  name: local
contexts:
- context:
    cluster: local
    namespace: default
    user: user
  name: Default
current-context: Default
kind: Config
preferences: {}
users:
- name: user
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrakNDQVRlZ0F3SUJBZ0lJZHBXSjhDbmd5WDR3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOalE1TnpNeE5UYzJNQjRYRFRJeU1EUXhNakF5TkRZeE5sb1hEVEl6TURReApNakF5TkRZeE5sb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJHcGdQTW9ycFQ2ZG42TXoKQ1k1dHZkK1BJZ3ZSODJCelAyWHRNbTdVRE1HMlpRVHdabkg5VFRJbWlHRVBBRXEzWHNPd1dFVVlLa3dwTVQ5eAp3U0VPMVFTalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUWpZR0lGNU1UbVdCMXlod3JxanBTUVVXdVBxakFLQmdncWhrak9QUVFEQWdOSkFEQkcKQWlFQTZ2aUVubHZWd0RRQXJKcWlmdWs4ZnN5NGk3MmJsWWFDYlZkSHFtbjJVelFDSVFETTg3UytIaWVPMVUxdgpSWUZNNjM0Zk9WZ3lUdERGOVVUZUtBbUJ6czArK2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCZGpDQ0FSMmdBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwClpXNTBMV05oUURFMk5EazNNekUxTnpZd0hoY05Nakl3TkRFeU1ESTBOakUyV2hjTk16SXdOREE1TURJME5qRTIKV2pBak1TRXdId1lEVlFRRERCaHJNM010WTJ4cFpXNTBMV05oUURFMk5EazNNekUxTnpZd1dUQVRCZ2NxaGtqTwpQUUlCQmdncWhrak9QUU1CQndOQ0FBVGdiT3ZxK1R0Tk1pTUcrVW1XV2xCVTNKcUJpcUE0anlpTHk2YkdxLy9zCi9Ca0wvZFovdTFIYkdVL3FxNjJxMkM2K1hWVWo5QS9lUGdRWDZXbFU5cGh3bzBJd1FEQU9CZ05WSFE4QkFmOEUKQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVJMkJpQmVURTVsZ2Rjb2NLNm82VQprRkZyajZvd0NnWUlLb1pJemowRUF3SURSd0F3UkFJZ090S1hRTWlFNlA3UDhtVGZNR0d2cHpCcXpCTEhpVzRDCkxpaFB5eTBVM1NJQ0lEaUVlcHJoWUR3QzZmNnJtaHBaaFBCNFV6ZEdUdlAzbWRNeG83dkhsWS9JCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUMwRExGNHBrdFo3SzNzTE1xYTVDM2VXQjNpWDhtQU9aTkpJd3ZBS1JjNWdvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFYW1BOHlpdWxQcDJmb3pNSmptMjkzNDhpQzlIellITS9aZTB5YnRRTXdiWmxCUEJtY2YxTgpNaWFJWVE4QVNyZGV3N0JZUlJncVRDa3hQM0hCSVE3VkJBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
