apiVersion: v1
clusters:
- cluster:
    server: https://10.136.152.227:30008
    insecure-skip-tls-verify: true
  name: local
contexts:
- context:
    cluster: local
    namespace: default
    user: user
  name: Default
current-context: Default
kind: Config
preferences: {}
users:
- name: user
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrRENDQVRlZ0F3SUJBZ0lJQ2E3RjNReDUxRGd3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOalE1TnpNd05UZzVNQjRYRFRJeU1EUXhNakF5TWprME9Wb1hEVEl6TURReApNakF5TWprME9Wb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJPdEdSM3IwQTkzbnZRajUKek5iMWRwVHI3L0sxdW5KSmd6K3FPRkNZMXlSeDFqRXgyUzVmOTQ1d0ptY0VMUXhqQ1RQdW04TUlESUNkYm9GdApGRzlKV1BTalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUWVzNllKRWM1MmdJZDVRSklMeTVoeGlCT3RYREFLQmdncWhrak9QUVFEQWdOSEFEQkUKQWlBYkovM0RVUDE2Vms5UGVCUkdaNGh5UWdFTlgxbEhMcEdYOGc2WXgzanVpQUlnQ25vMXN1dVdERUFSMUc4YQpZUDlmZXVqYmhVZUsweXhySlJJdndSU3YxQU09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUyTkRrM016QTFPRGt3SGhjTk1qSXdOREV5TURJeU9UUTVXaGNOTXpJd05EQTVNREl5T1RRNQpXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUyTkRrM016QTFPRGt3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSZ09xcGg1Q1dyYytncTUwSGlwbEJhb1ozd0pGUVhBTUFBeTJKWldqaWEKQWtSbWlCc2xNYXRYdjJWQUtLUWc1dHJubDBhZ3JiT2ZsbDJSaFFkZjE5MktvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUhyT21DUkhPZG9DSGVVQ1NDOHVZCmNZZ1RyVnd3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQUlQYkFObzlybCtjdWtPNWxzcFl5ai8zWWRVbTltV3YKeTFqT2hmTGhXb3ZZQWlFQWtqNUwvN05aUzRqUFcvRysvZ0xHcHhGMENkVlVuNTgwLy9oYWd3cTZ0alk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUtXMTVISzFydmdQOGMrQUtTdGVqRTE1b1ZXak9tbXRLQzFVOFVuYmlWdUtvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFNjBaSGV2UUQzZWU5Q1BuTTF2VjJsT3Z2OHJXNmNrbURQNm80VUpqWEpISFdNVEhaTGwvMwpqbkFtWndRdERHTUpNKzZid3dnTWdKMXVnVzBVYjBsWTlBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
