apiVersion: v1
clusters:
- cluster:
    server: https://10.136.152.227:30010
    insecure-skip-tls-verify: true
  name: local
contexts:
- context:
    cluster: local
    namespace: default
    user: user
  name: Default
current-context: Default
kind: Config
preferences: {}
users:
- name: user
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrakNDQVRlZ0F3SUJBZ0lJUWpDRzRrOXhlaWt3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOalE1TnpNeE1EUXlNQjRYRFRJeU1EUXhNakF5TXpjeU1sb1hEVEl6TURReApNakF5TXpjeU1sb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJBWnd3QXQyMCtuQ3JIdTkKQjJZamdOQjBzVEgyMHpHSlQ2d1dIWklzOTRZdnhGRUdmK2xEZjhrS2dpZWU3QnBKeGdjVEcwZFdJMDU3V1gzQQpOczhwNVhLalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUzNYZVlMazdIYy9UQ2JaN0d5STViZmdOY3dvVEFLQmdncWhrak9QUVFEQWdOSkFEQkcKQWlFQXRMZ3Z5YjUvbTRsRkQ5ZHNtbUpZUXNXM1Yvc0o3ZlYvUFJpNGRJM0o3LzhDSVFEdHpUakdnaWJjVG1pQQpvcGhUdmplNlJKVWo0UkRleUNpaGc0MVZCLzcwT2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCZURDQ0FSMmdBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwClpXNTBMV05oUURFMk5EazNNekV3TkRJd0hoY05Nakl3TkRFeU1ESXpOekl5V2hjTk16SXdOREE1TURJek56SXkKV2pBak1TRXdId1lEVlFRRERCaHJNM010WTJ4cFpXNTBMV05oUURFMk5EazNNekV3TkRJd1dUQVRCZ2NxaGtqTwpQUUlCQmdncWhrak9QUU1CQndOQ0FBUyt3SEpDT3kxb054MTExR3dodWhybnk4T0ZMam5XSEt5VXlPbnJGVEZXCjlBMEdRZXo4Ui9NWC9MQ1p6WlNzazVFckRVUEFxYmg2MDBuMEhSSjlhUlgzbzBJd1FEQU9CZ05WSFE4QkFmOEUKQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVV0MTNtQzVPeDNQMHdtMmV4c2lPVwozNERYTUtFd0NnWUlLb1pJemowRUF3SURTUUF3UmdJaEFOeXFPRDlyZktOcDluLy9BZVNMMlVNcnZkUTN3S2pDCjl6MTRHOTZiKy8yWkFpRUFxbjFvL3dwUEdvTlZEUHF5bDdSdk9HVmJEMkJEbHlDV0traGRld0YwdHZBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUI1MjZIUjMyVjVweFdOdXNyTC96NmU0Mm5Sb3IzVFJOdWxIcFBhNDBHczhvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFQm5EQUMzYlQ2Y0tzZTcwSFppT0EwSFN4TWZiVE1ZbFByQllka2l6M2hpL0VVUVovNlVOLwp5UXFDSjU3c0drbkdCeE1iUjFZalRudFpmY0EyenlubGNnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
