apiVersion: v1
clusters:
- cluster:
    server: https://10.136.152.227:30015
    insecure-skip-tls-verify: true
  name: local
contexts:
- context:
    cluster: local
    namespace: default
    user: user
  name: Default
current-context: Default
kind: Config
preferences: {}
users:
- name: user
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrRENDQVRlZ0F3SUJBZ0lJUTRlMXFsRVdObFl3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOalE1TnpNeU1qWXdNQjRYRFRJeU1EUXhNakF5TlRjME1Gb1hEVEl6TURReApNakF5TlRjME1Gb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJPMGdMUHBBbGcwRnppbzkKT2k5V1dJRjZCM2VSZHk5Ny9HREltOHVaNG9jakJKTWszNFJEV1BkT0F4eXgrNkJTeXNUMS9tMDgzSU5CTURJSgo5NXVyMlZLalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCVCt0SzRGRkpoL2NTSlRiTUZxOU5NbzdJU2VSakFLQmdncWhrak9QUVFEQWdOSEFEQkUKQWlBMUEvY1JUandBUHlZL3hCMDB3SERDUGl4aUJkZDBaL01QWUhkRVlpOGdUQUlnVFJReVhEUTBBSjJZZUFQWApRTXY4RVNoTElGaTVTZ1NrcXFYMW1Fdk5RRFk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUyTkRrM016SXlOakF3SGhjTk1qSXdOREV5TURJMU56UXdXaGNOTXpJd05EQTVNREkxTnpRdwpXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUyTkRrM016SXlOakF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSaWtnNmFabXB5azhXK3UzRDBYSElmc2ZSQWtoQmRpcms4UEdXcTBxWGcKSENwTVlWUHRaRnZRV2dTMk9tQ3AzVHNsZ2o0ME5jdUlYbnhSdWFaMTJWOWlvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVS9yU3VCUlNZZjNFaVUyekJhdlRUCktPeUVua1l3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnQXMrdVlNVkN1em9raWdWN1RaMGFxY3F0VGR2b2RqKzkKanNKR0V4SzFtTG9DSVFDdEdXVG5wNTdORGlDUjFCVUczSzhhUVZKcFNLSTBudkRsRWtTTUpjTUswUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUdLYndyZlNWR3FhNjYzb0pzakFhdytQdWx4cVJ2emRwdDZYK2JJLzF5STZvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFN1NBcytrQ1dEUVhPS2owNkwxWllnWG9IZDVGM0wzdjhZTWlieTVuaWh5TUVreVRmaEVOWQo5MDRESExIN29GTEt4UFgrYlR6Y2cwRXdNZ24zbTZ2WlVnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
